# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfe55e49362587d7a1d7fcf1367a9d4a"
name = "custom-wishlist"
application_url = "https://cus-wishlist-app-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers"

[auth]
redirect_urls = ["https://cus-wishlist-app-production.up.railway.app/auth/callback"]

[app_proxy]
url = "/wishlist-proxy"
subpath = "wishlist"
prefix = "apps"
