name = "wishlist-button"
handle = "wishlist-button"
type = "theme"
uid = "c992d8a7-d734-ca5b-238e-282fcc9d779353d727b0"

[settings]
  [[settings.fields]]
  key = "app_url"
  type = "text"
  name = "App URL"
  info = "Your app's backend URL (e.g. https://yourapp.com)"
